### ISSUE TITLE
[BUG] Breaking change in Tibber websocket subscriptions in December 2022 will break livefeed functionality

### ISSUE THREAD

**Issue by JoshuaDodds** [BeatsuDev/tibber.py#16]
## Describe the bug
This will be an upcoming bug within a few weeks.  Read more about the change here:

https://developer.tibber.com/docs/overview#breaking-websocket-change

**Comment by JoshuaDodds** [comment]
Tibber dev team recommends [This](https://github.com/Danielhiversen/PyGraphqlWebsocketManager) as an option for compliant client implementations.  Maybe its useful?

**Comment by Bernving** [comment]
Might have solved the issue.  I bit too new to github to provide the solution

**Comment by BeatsuDev** [comment]
I believe this issue is now fixed in the latest commit (https://github.com/BeatsuDev/tibber.py/commit/53f76d3847310927bb8c873a800f3afb21a18f9a). Some new issues have occurred regarding fetching consumption and production, but after that's fixed too, I'll release the update. Thanks a lot for bringing the breaking changes to my attention! I'll keep this issue open for now just to see how the update deals with the changes.

**Comment by JoshuaDodds** [comment]
Hi @BeatsuDev this looks like it will handle the changes for sure! nice work!  I think you might also need to update the API endpoint in __init__.py as well.   This has been changed/is being changed.  They also are making a change that the endpoint should be queried for (i imagine so that they can change it if they need to)

See this info from the link above:

_After the change the URL must be queried via GraphQL (see example below) and client must support [graphql-transport-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) sub-protocol._
```

{
  viewer {
    websocketSubscriptionUrl
  }
}

```
Currently, the URL returned is wss://websocket-api.tibber.com/v1-beta/gql/subscriptions

But as i understand it,  they could change that at any time so maybe makes sense that your code queries for it on startup or something?

**Comment by BeatsuDev** [comment]
> Hi @BeatsuDev this looks like it will handle the changes for sure! nice work! I think you might also need to update the API endpoint in **init**.py as well. This has been changed/is being changed. They also are making a change that the endpoint should be queried for (i imagine so that they can change it if they need to)
> 
> See this info from the link above:
> 
> _After the change the URL must be queried via GraphQL (see example below) and client must support [graphql-transport-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) sub-protocol._
> 
> ```
> 
> {
>   viewer {
>     websocketSubscriptionUrl
>   }
> }
> ```
> 
> Currently, the URL returned is wss://websocket-api.tibber.com/v1-beta/gql/subscriptions
> 
> But as i understand it, they could change that at any time so maybe makes sense that your code queries for it on startup or something?

I've changed that too in the latest version (0.2.0) which is out on pypi now. I've noticed now that I've just forgotten to remove the endpoint constant (it's not being used in the code anymore). (See https://github.com/BeatsuDev/tibber.py/blob/master/tibber/types/home.py#L218)

**Comment by JoshuaDodds** [comment]
Hi @BeatsuDev, 

Thanks for the updates!  I am however getting a lot of ouput on STDOUT now from home.start_live_feed() which was not there before.  Basically its the whole data structure response logged to stdout on every websocket response.  I can't seem to find what introduced this with a quick glance at the changes.   Any idea?   It's extremely noisy in the logs....

**Comment by BeatsuDev** [comment]
> Hi @BeatsuDev,
> 
> Thanks for the updates! I am however getting a lot of ouput on STDOUT now from home.start_live_feed() which was not there before. Basically its the whole data structure response logged to stdout on every websocket response. I can't seem to find what introduced this with a quick glance at the changes. Any idea? It's extremely noisy in the logs....

Very weird... I don't receive any errors when running it on my end with the demo token...
![image](https://user-images.githubusercontent.com/35773677/204688771-472a06c9-8f18-49b3-9814-436982f42ddf.png)

Could you send me the code that produces the output, and perhaps a snippet of the output?

**Comment by JoshuaDodds** [comment]
> Perhaps you have a logger instantiated and set to debug/info (or maybe this is done by default on whatever system you're running)? My debug logging can be quite verbose... I added this quite recently: https://github.com/BeatsuDev/tibber.py/blob/master/tibber/types/home.py#L241

Yes this turned out to be the issue... something with log levels somewhere have changed and now im getting output that i did not used to get before.... I need to change log level to WARN to get rid of the output... but it's strange that the behavior suddenly changed like this.  Maybe the change in the tibber API has resulted in consuming a newer version of the Tibber API which has changed in some way?

On an unrelated note.... there seems to be another issue with this new endpoint and it seems much more restrictive about the number of consumers connected to the live feed API.  Limits it to a single connection.  If you break with ctrl-c or something from the command line while using a real Token and not the demo one and run it again you get:

```websockets.exceptions.ConnectionClosedError: received 4429 (private use) Too many open connections on this server: 2; then sent 4429 (private use) Too many open connections on this server: 2```

Could it help if we added something like a __del__() method on home that cleans and closes the connection on exiting or maybe specify some timeouts on the WebsocketsTransport object.  Specifically define some sane values for close, keep-alive, and ack timeouts for example?

Just some ideas... for now im not upgrading as it still seems like not a direct drop-in replacement for 0.1.1.... I need to test and adjust a bit more...

**Comment by BeatsuDev** [comment]
> > Perhaps you have a logger instantiated and set to debug/info (or maybe this is done by default on whatever system you're running)? My debug logging can be quite verbose... I added this quite recently: https://github.com/BeatsuDev/tibber.py/blob/master/tibber/types/home.py#L241
> 
> Yes this turned out to be the issue... something with log levels somewhere have changed and now im getting output that i did not used to get before.... I need to change log level to WARN to get rid of the output... but it's strange that the behavior suddenly changed like this.  Maybe the change in the tibber API has resulted in consuming a newer version of the Tibber API which has changed in some way?
> 
> On an unrelated note.... there seems to be another issue with this new endpoint and it seems much more restrictive about the number of consumers connected to the live feed API.  Limits it to a single connection.  If you break with ctrl-c or something from the command line while using a real Token and not the demo one and run it again you get:
> 
> ```websockets.exceptions.ConnectionClosedError: received 4429 (private use) Too many open connections on this server: 2; then sent 4429 (private use) Too many open connections on this server: 2```
> 
> Could it help if we added something like a __del__() method on home that cleans and closes the connection on exiting or maybe specify some timeouts on the WebsocketsTransport object.  Specifically define some sane values for close, keep-alive, and ack timeouts for example?
> 
> Just some ideas... for now im not upgrading as it still seems like not a direct drop-in replacement for 0.1.1.... I need to test and adjust a bit more...  
> 
> btw, the ouput i was getting looks like this:
> ```
> 2022-11-30 09:34:31 cerbomoticzGx: <<< {"id":"2","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2022-11-30T09:34:29.000+01:00","power":0,"lastMeterConsumption":30292.401,"accumulatedConsumption":12.862,"accumulatedProduction":0.238,"accumulatedConsumptionLastHour":0.002,"accumulatedProductionLastHour":0.02,"accumulatedCost":4.631697,"accumulatedReward":0.10933,"currency":"EUR","minPower":0,"averagePower":1342.9,"maxPower":13279,"powerProduction":5,"powerProductionReactive":null,"minPowerProduction":0,"maxPowerProduction":901,"lastMeterProduction":1082.304,"powerFactor":null,"voltagePhase1":235.9,"voltagePhase2":234.5,"voltagePhase3":232.9,"currentL1":2,"currentL2":1,"currentL3":1,"signalStrength":null}}}}
> 2022-11-30 09:34:32 cerbomoticzGx: <<< {"id":"2","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2022-11-30T09:34:30.000+01:00","power":0,"lastMeterConsumption":30292.401,"accumulatedConsumption":12.862,"accumulatedProduction":0.238,"accumulatedConsumptionLastHour":0.002,"accumulatedProductionLastHour":0.02,"accumulatedCost":4.631697,"accumulatedReward":0.10933,"currency":"EUR","minPower":0,"averagePower":1342.9,"maxPower":13279,"powerProduction":14,"powerProductionReactive":null,"minPowerProduction":0,"maxPowerProduction":901,"lastMeterProduction":1082.304,"powerFactor":null,"voltagePhase1":235.9,"voltagePhase2":234.4,"voltagePhase3":233.1,"currentL1":1,"currentL2":1,"currentL3":1,"signalStrength":null}}}}
> ```
> 
> each time the callback function is called.

Without having checked, I think the new INFO logs could be from the gql.transport.WebsocketTransport class in the gql library (I switched to using that instead). I'll look into possible solutions later today.

As for the connections to the websocket, I'll try adding a `__del__` function as you mentioned. I don't have a Tibber Pulse, so I can't test the live measurement data with a real token. So thanks a lot for bringing up this problem!

**Comment by BeatsuDev** [comment]
I actually couldn't find any INFO logger statements in either my own code in home.py or in the gql.Client or gql.transport.WebsocketTransport classes... What's the name of the logger? Perhaps that could give us a clue as to where it's coming from.

**Comment by BeatsuDev** [comment]
@JoshuaDodds I created a new issue #20 which is probably related to the error you get when restarting the real-time data loop after interrupting it.

**Comment by JoshuaDodds** [comment]
> I actually couldn't find any INFO logger statements in either my own code in home.py or in the gql.Client or gql.transport.WebsocketTransport classes... What's the full path name of the logger (https://docs.python.org/3/library/logging.html#logrecord-attributes) %(pathname)s? Perhaps that could give us a clue as to where it's coming from.

Ok looks like its coming from gql indeed... here is logging output with full pathname attribute added:

`2022-12-01 13:10:55 cerbomoticzGx: /usr/local/lib/python3.10/dist-packages/gql/transport/websockets_base.py: <<< {"id":"2","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2022-12-01T13:10:55.000+01:00","power":1928,"lastMeterConsumption":37618.015,"accumulatedConsumption":46.456,"accumulatedProduction":0,"accumulatedConsumptionLastHour":0.373,"accumulatedProductionLastHour":0,"accumulatedCost":224.075465,"accumulatedReward":0,"currency":"SEK","minPower":1054,"averagePower":3523.5,"maxPower":8474,"powerProduction":0,"powerProductionReactive":1415,"minPowerProduction":0,"maxPowerProduction":0,"lastMeterProduction":6412.171,"powerFactor":0.806,"voltagePhase1":230.4,"voltagePhase2":229.4,"voltagePhase3":232,"currentL1":3.1,"currentL2":4.6,"currentL3":4,"signalStrength":null}}}}`

**Comment by JoshuaDodds** [comment]
This stops the log spam for me.

`logging.getLogger("gql.transport.websockets").setLevel(logging.WARNING)`

added to the top of my module after imports.

**Comment by JoshuaDodds** [comment]
I would say feel free to close this one out and thanks for all the love on this project in the last week!! Much appreciated!

**Comment by BeatsuDev** [comment]
> This stops the log spam for me.
> 
> `logging.getLogger("gql.transport.websockets").setLevel(logging.WARNING)`
> 
> added to the top of my module after imports.
> 
> If you have a look at that websockets_base.py its completely littered with unnecessary log.info()'s with stuff that really should be set to debug level if you ask me. My global project logging configuration sets default level to info so this is why im getting those logs i guess but this is far more information coming from the gql package than what i would consider "informational". :D :D

I didn't check the base websocket class for logger messages! Great catch.


> I would say feel free to close this one out and thanks for all the love on this project in the last week!! Much appreciated!

Thanks a lot for all the feedback! It's been helpful to get fixes out there.
