### ISSUE TITLE
Python 3.7 and 3.8 builds are failing because of @classmethod and @property on same method

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/tibber.py#4]
The Python 3.7 and 3.8 builds are failing because the `@classmethod` decorator and the `@property` decorator cannot be used on the same method in these versions. Since Python 3.9 was anyway released in October 2020 and this module is anyway in early development stages, I think it will be okay to require Python 3.9+ for this module. If this should be changed, it can be done in the future.

**Comment by BeatsuDev** [comment]
Reopening this because I would like to support versions 3.7 and 3.8 too.

**Comment by seh-len** [comment]
Is it very complex to convert tibber.py for python 3.7? I would hate to have to convert my running python 3.7 installation to 3.9, as I'm not even sure if all packages would still work after that. But I also understand that this is not such a high priority for you right now. So what would I have to do to make tibber.py work with python 3.7?

**Comment by BeatsuDev** [comment]
![image](https://github.com/BeatsuDev/tibber.py/assets/35773677/e4e2c24f-ca40-4b38-9d70-52786669701a)

After doing the changes I mentioned above I had some type errors. After adding `from __future__ import annotations` to every file in the `tibber/types/` directory, it worked! 😄

I'll upload a temporary branch for you @seh-len. Hopefully you can clone that and it will work!

**Comment by BeatsuDev** [comment]
I've actually changed my mind. I've merged the changes into the master branch. The changes were very minor and will likely not be noticed by end users. Once I have time to thoroughly go through the project and fix some other stuff, I'll upload the version to pypi. So in the next version of tibber.py, versions 3.7 and 3.8 will be supported👍 For now you can clone the tibber.py repository and import it locally.

**Comment by seh-len** [comment]
Thank you very much! It works great!
